# Generated by Django 3.2.23 on 2023-11-14 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('product_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('alt_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('notes', models.TextField()),
                ('contact_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('already_synchronized', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.appointmentseries')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.appointmenttype')),
            ],
        ),
    ]
