# Generated by Django 3.2.23 on 2023-12-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentseries',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='appointment',
            name='cal_id',
            field=models.TextField(null=True),
        ),
    ]
