# Generated by Django 3.2.23 on 2023-12-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20231211_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentseries',
            name='quantity',
        ),
    ]
