# Generated by Django 3.2.23 on 2023-12-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20231218_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttype',
            name='price',
            field=models.FloatField(default=60),
            preserve_default=False,
        ),
    ]
